version: 2

updates:
# Terraform - One entry per thing we want to scan as per https://github.com/dependabot/dependabot-core/issues/649
  - package-ecosystem: "terraform"
    directory: "/terraform/boundary"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/hcp-cloud"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/network"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/tfc-agent"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/vault"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/vpn"
    schedule:
      interval: "daily"

